name: tinstgrame
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.2
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.2
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.11
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.7
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^5.4.4
  hooks_riverpod: ^2.1.3
  image: ^4.0.15
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  lottie: ^2.2.0
  share_plus: ^6.3.1
  url_launcher: ^6.1.9
  uuid: ^3.0.7
  video_player: ^2.5.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/data_not_found.json
    - assets/animations/loading.json
    - assets/animations/empty.json
    - assets/animations/error.json
    - assets/animations/small_error.json
  